# Generated by Django 3.0 on 2022-01-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_companies_designation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='desig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.designation'),
            preserve_default=False,
        ),
    ]
