# Generated by Django 3.0 on 2022-01-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_account_desig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='desig',
        ),
    ]
